[project]
name = "rl-exercices"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gymnasium[toy-text]>=1.2.3",
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
    "seaborn>=0.13.2",
]
